import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Arma from 'App/Models/Arma'

export default class extends BaseSeeder {
  public static environment = ['development','testing']
  public async run () {
    // Write your database queries inside the run method

    await Arma.createMany([
      {
        "id": 1,
        "livrete": "ABC123",
        "serie": "123456789",
        "marca": "Glock",
        "modelo": "G17",
        "tipo": "Pistola",
        "is_usuario": true,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 2,
        "livrete": "DEF456",
        "serie": "987654321",
        "marca": "Sig Sauer",
        "modelo": "P226",
        "tipo": "Pistola",
        "is_usuario": false,
        "is_singular": false,
        "is_efectivo": true,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 3,
        "livrete": "GHI789",
        "serie": "24681012",
        "marca": "Heckler & Koch",
        "modelo": "MP5",
        "tipo": "Metralhadora",
        "is_usuario": false,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": true,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 4,
        "livrete": "JKL101",
        "serie": "12162024",
        "marca": "Remington",
        "modelo": "M870",
        "tipo": "Espingarda",
        "is_usuario": false,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": true
      },
      {
        "id": 5,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": false,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": true,
        "is_ent_externa": false
      },
      {
        "id": 6,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": false,
        "is_singular": false,
        "is_efectivo": true,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 7,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": false,
        "is_singular": false,
        "is_efectivo": true,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 8,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": false,
        "is_singular": true,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 9,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": false,
        "is_singular": true,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 10,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": true,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 11,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": true,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 12,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": true,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 13,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": true,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 14,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": true,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 15,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": true,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 16,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": true,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 17,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": true,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 18,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": true,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 19,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": false,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": true,
        "is_ent_externa": false
      },
      {
        "id": 20,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle", 
        "is_usuario": false,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": true,
        "is_ent_externa": false
      },
      {
        "id": 21,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": false,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": true
      },
      {
        "id": 22,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": false,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": false,
        "is_comando_mun": false,
        "is_ent_externa": true
      },
      {
        "id": 23,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": false,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": true,
        "is_comando_mun": false,
        "is_ent_externa": false
      },
      {
        "id": 24,
        "livrete": "MNO123",
        "serie": "222333444",
        "marca": "Barrett",
        "modelo": "M107",
        "tipo": "Rifle",
        "is_usuario": false,
        "is_singular": false,
        "is_efectivo": false,
        "is_empresa_seg": true,
        "is_comando_mun": false,
        "is_ent_externa": false
      }
    ]
    )



  }
}
